### ISSUE TITLE
Bot Verification

### ISSUE THREAD

**Issue by meneken17** [jacknight/buzzer#5]
I can not add the bot to my server.
Apparently your bot is installed on 100 servers and discord requires some additional verifications.
It shows me an error message, which redirects to this article:
https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting

**Comment by jacknight** [comment]
Thanks for wanting to use the bot. I already submitted the bot for
verification 3 weeks ago, Discord is just moving very slow on it. Nothing I
can do unfortunately.

**Comment by Hamashi** [comment]
Hi, you should add a part to the readme to explain how to run the bot in a local environment while waiting for the approval from Discord

**Comment by jacknight** [comment]
> Hi, you should add a part to the readme to explain how to run the bot in a local environment while waiting for the approval from Discord

https://github.com/jacknight/buzzer#run-locally

Let me know if that works for you, I didn't really try and test those steps myself.

**Comment by Hamashi** [comment]
By default, mongoDB doesn't have any user, so it doesn't work, i'll try adding one later

**Comment by jacknight** [comment]
> By default, mongoDB doesn't have any user, so it doesn't work, i'll try adding one later

You can always fork it and change the mongo url so you don't need the name.  This line:
https://github.com/jacknight/buzzer/blob/2d2906822d0c9778a85ba86888adbe6bb06abe98/bot.js#L76
